# Navigation Links:
# To link a homepage widget, specify the URL as a hash `#` followed by
# the filename of the desired widget in your `content/home/` folder.
#
# The weight parameter defines the order that the links will appear in.

main:
  - name: "Home"
    weight: 10
  - name: People
    url: "/people"
    weight: 20
  - name: Management
    parent: People
    url: "/team/management"
    weight: 21
  - name: Track Leaders
    parent: People
    url: "/team/track-leaders"
    weight: 23
  - name: Students
    parent: People
    url: "/team/students"
    weight: 24
  - name: Research
    url: "/research"
    weight: 30
  - name: Software Analytics
    parent: Research
    url: "/research/software-analytics"
    weight: 31
  - name: Data Integration
    parent: Research
    url: "/research/data-integration"
    weight: 32
  - name: Incident Management
    parent: Research
    url: "/research/incident-management"
    weight: 33
  - name: Ml Models at Scale
    parent: Research
    url: "/research/ml-models-at-scale"
    weight: 34
  - name: Reinforcement Learning
    parent: Research
    url: "/research/reinforcement-learning"
    weight: 36
  - name: AI-based Quality and Testing
    parent: Research
    url: "/research/ai-based-quality-and-testing"
    weight: 37
  - name: Natural Language Processing
    parent: Research
    url: "/research/natural-language-processing"
    weight: 38
  - name: Trustworthy AI
    parent: Research
    url: "/research/trustworthy-ai"
    weight: 39
  - name: Quantum Computing
    parent: Research
    url: "/research/quantum-computing"
    weight: 40
  - name: Publications
    url: "/publications"
    weight: 50
  - name: Events
    url: "/events"
    weight: 60
  - name: Vacancies
    url: "/current-vacancies"
    weight: 70
  - name: About
    url: "/about"
    weight: 80
  - name: General Information
    parent: About
    url: "/about/general-information"
    weight: 81
  - name: New Students
    parent: About
    url: "/about/new-students"
    weight: 82
  

