exclude: [".gitignore", "README.md", "Rakefile", ]
highlighter: rouge
future: true

title : AI for Fintech Research
tagline:
author :
  name : Arie van Deursen
  github : serg-delft
  twitter : serg_delft

url:           "https://se.ewi.tudelft.nl/ai4fintech"
