exclude: [".gitignore", "README.md", "Rakefile", ]
highlighter: rouge
future: true

relative_permalinks: false

title : AI for Fintech Research
tagline:
author :
  name : Arie van Deursen
  github : serg-delft
  twitter : Ai4Fintech

baseurl: "ai4fintech" # the subpath of your site, e.g. /blog
url: "https://se.ewi.tudelft.nl/" # the base hostname & protocol for your site, e.g.

collections:
  tracks :
    output: true
    sort_by: track-id
