exclude: [".gitignore", "README.md", "Rakefile", ]
highlighter: rouge
future: true

relative_permalinks: false

title : AI for Fintech Research
tagline:
author :
  name : Arie van Deursen
  github : serg-delft
  twitter : serg_delft

collections:
  tracks :
    output: true
    sort_by: track-id
